---
services:
  debrid_cleanup:
    build: .
    container_name: debrid_cleanup
    labels:
      autoheal-app: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./healthcheck:/healthcheck
      - /data:/data
      - /mnt:/mnt:rslave
    restart: on-failure:2
    command: "python3 discard.py --no-confirm"